<?php
/** @package Bancotccdavi::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("AlunoMap.php");

/**
 * AlunoDAO provides object-oriented access to the aluno table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Bancotccdavi::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class AlunoDAO extends Phreezable
{
	/** @var int */
	public $IdAluno;

	/** @var string */
	public $Nome;

	/** @var string */
	public $Cpf;

	/** @var string */
	public $Rg;

	/** @var string */
	public $Logradouro;

	/** @var string */
	public $Cep;

	/** @var int */
	public $Numero;

	/** @var string */
	public $Complemento;

	/** @var int */
	public $Prontuario;

	/** @var int */
	public $IdRespAluno;


	/**
	 * Returns a dataset of Frequencia objects with matching IdAlunoFreq
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdFreqFrequencias($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "frequencia_ibfk_1", $criteria);
	}

	/**
	 * Returns a dataset of Notas objects with matching IdAlunoNotas
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdNotasNotass($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "notas_ibfk_1", $criteria);
	}

	/**
	 * Returns a dataset of Observacoes objects with matching IdAlunoObs
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdObsObservacoess($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "observacoes_ibfk_1", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of IdRespAluno
	 * @return Responsavel
	 */
	public function GetIdRespAlunoResponsavel()
	{
		return $this->_phreezer->GetManyToOne($this, "aluno_ibfk_1");
	}


}
?>