<?php
/** @package Bancotccdavi::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("AtribuicaoMap.php");

/**
 * AtribuicaoDAO provides object-oriented access to the atribuicao table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Bancotccdavi::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class AtribuicaoDAO extends Phreezable
{
	/** @var int */
	public $Atribuicao;

	/** @var int */
	public $ProfAtr;

	/** @var int */
	public $TurmaAtr;

	/** @var int */
	public $DiscAtr;


	/**
	 * Returns a dataset of Frequencia objects with matching IdAtribuicaoFreq
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdFreqFrequencias($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "frequencia_ibfk_2", $criteria);
	}

	/**
	 * Returns a dataset of Notas objects with matching IdAtribuicaoNotas
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdNotasNotass($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "notas_ibfk_2", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of ProfAtr
	 * @return Professor
	 */
	public function GetProfAtrProfessor()
	{
		return $this->_phreezer->GetManyToOne($this, "atribuicao_ibfk_1");
	}

	/**
	 * Returns the foreign object based on the value of TurmaAtr
	 * @return Turma
	 */
	public function GetAtrTurma()
	{
		return $this->_phreezer->GetManyToOne($this, "atribuicao_ibfk_2");
	}

	/**
	 * Returns the foreign object based on the value of DiscAtr
	 * @return Disciplina
	 */
	public function GetDiscAtrDisciplina()
	{
		return $this->_phreezer->GetManyToOne($this, "atribuicao_ibfk_3");
	}


}
?>