<?php
/** @package Bancotccdavi::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("CalendarioMap.php");

/**
 * CalendarioDAO provides object-oriented access to the calendario table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Bancotccdavi::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class CalendarioDAO extends Phreezable
{
	/** @var int */
	public $IdCalendario;

	/** @var date */
	public $Data;

	/** @var string */
	public $Aviso;

	/** @var int */
	public $IdTurmaCalen;


	/**
	 * Returns the foreign object based on the value of IdTurmaCalen
	 * @return Turma
	 */
	public function GetIdCalenTurma()
	{
		return $this->_phreezer->GetManyToOne($this, "calendario_ibfk_1");
	}


}
?>