<?php
/** @package Bancotccdavi::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("DisciplinaMap.php");

/**
 * DisciplinaDAO provides object-oriented access to the disciplina table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Bancotccdavi::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class DisciplinaDAO extends Phreezable
{
	/** @var int */
	public $IdDisc;

	/** @var string */
	public $Nome;

	/** @var int */
	public $CargaHoraria;


	/**
	 * Returns a dataset of Atribuicao objects with matching DiscAtr
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetDiscAtrAtribuicaos($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "atribuicao_ibfk_3", $criteria);
	}


}
?>