<?php
/** @package Bancotccdavi::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ObservacoesMap.php");

/**
 * ObservacoesDAO provides object-oriented access to the observacoes table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Bancotccdavi::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ObservacoesDAO extends Phreezable
{
	/** @var int */
	public $IdObs;

	/** @var string */
	public $Observacoes;

	/** @var int */
	public $IdAlunoObs;

	/** @var int */
	public $IdRespObs;


	/**
	 * Returns the foreign object based on the value of IdAlunoObs
	 * @return Aluno
	 */
	public function GetIdObsAluno()
	{
		return $this->_phreezer->GetManyToOne($this, "observacoes_ibfk_1");
	}

	/**
	 * Returns the foreign object based on the value of IdRespObs
	 * @return Responsavel
	 */
	public function GetIdRespObsResponsavel()
	{
		return $this->_phreezer->GetManyToOne($this, "observacoes_ibfk_2");
	}


}
?>