<?php
/** @package Bancotccdavi::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ProfessorMap.php");

/**
 * ProfessorDAO provides object-oriented access to the professor table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Bancotccdavi::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ProfessorDAO extends Phreezable
{
	/** @var int */
	public $IdProfessor;

	/** @var string */
	public $Nome;

	/** @var string */
	public $Cpf;

	/** @var string */
	public $Rg;

	/** @var string */
	public $Logradouro;

	/** @var string */
	public $Cep;

	/** @var int */
	public $Numero;

	/** @var string */
	public $Complemento;

	/** @var int */
	public $Prontuario;


	/**
	 * Returns a dataset of Atribuicao objects with matching ProfAtr
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetProfAtrAtribuicaos($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "atribuicao_ibfk_1", $criteria);
	}


}
?>