<?php
/** @package Bancotccdavi::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("SugestoesMap.php");

/**
 * SugestoesDAO provides object-oriented access to the sugestoes table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Bancotccdavi::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class SugestoesDAO extends Phreezable
{
	/** @var int */
	public $IdSug;

	/** @var string */
	public $Sugestoes;

	/** @var int */
	public $IdRespSug;


	/**
	 * Returns the foreign object based on the value of IdRespSug
	 * @return Responsavel
	 */
	public function GetIdRespSugResponsavel()
	{
		return $this->_phreezer->GetManyToOne($this, "sugestoes_ibfk_1");
	}


}
?>