<?php
/** @package Bancotccdavi::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("TurmaMap.php");

/**
 * TurmaDAO provides object-oriented access to the turma table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Bancotccdavi::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class TurmaDAO extends Phreezable
{
	/** @var int */
	public $IdTurma;

	/** @var string */
	public $Turma;

	/** @var string */
	public $Sala;

	/** @var int */
	public $Ano;


	/**
	 * Returns a dataset of Atribuicao objects with matching TurmaAtr
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetAtrAtribuicaos($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "atribuicao_ibfk_2", $criteria);
	}

	/**
	 * Returns a dataset of Calendario objects with matching IdTurmaCalen
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdCalenCalendarios($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "calendario_ibfk_1", $criteria);
	}


}
?>