<?php
/** @package Daviwebservice::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("AlunoMap.php");

/**
 * AlunoDAO provides object-oriented access to the aluno table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Daviwebservice::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class AlunoDAO extends Phreezable
{
	/** @var int */
	public $IdAluno;

	/** @var string */
	public $NomeAluno;

	/** @var int */
	public $Prontuario;

	/** @var int */
	public $IdAlunoResp;


	/**
	 * Returns a dataset of Frequencia objects with matching IdFrequenciaAluno
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdFrequenciaFrequencias($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "frequencia_ibfk_1", $criteria);
	}

	/**
	 * Returns a dataset of Login objects with matching IdLoginAluno
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdLoginLogins($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "login_ibfk_1", $criteria);
	}

	/**
	 * Returns a dataset of Materia objects with matching IdMateriaAluno
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdMateriaMaterias($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "materia_ibfk_2", $criteria);
	}

	/**
	 * Returns a dataset of Notas objects with matching IdNotasAluno
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdNotasNotass($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "notas_ibfk_1", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of IdAlunoResp
	 * @return Responsavel
	 */
	public function GetIdAlunoRespResponsavel()
	{
		return $this->_phreezer->GetManyToOne($this, "aluno_ibfk_1");
	}


}
?>