<?php
/** @package Daviwebservice::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("FrequenciaMap.php");

/**
 * FrequenciaDAO provides object-oriented access to the frequencia table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Daviwebservice::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class FrequenciaDAO extends Phreezable
{
	/** @var int */
	public $IdFrequencia;

	/** @var char */
	public $Frequencia;

	/** @var date */
	public $Dia;

	/** @var int */
	public $AulaDada;

	/** @var int */
	public $IdFrequenciaAluno;

	/** @var int */
	public $IdFrequenciaMateria;


	/**
	 * Returns the foreign object based on the value of IdFrequenciaAluno
	 * @return Aluno
	 */
	public function GetIdFrequenciaAluno()
	{
		return $this->_phreezer->GetManyToOne($this, "frequencia_ibfk_1");
	}

	/**
	 * Returns the foreign object based on the value of IdFrequenciaMateria
	 * @return Materia
	 */
	public function GetIdFrequenciaMateria()
	{
		return $this->_phreezer->GetManyToOne($this, "frequencia_ibfk_2");
	}


}
?>