<?php
/** @package Daviwebservice::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("LogSisMap.php");

/**
 * LogSisDAO provides object-oriented access to the log_sis table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Daviwebservice::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class LogSisDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var int */
	public $IoEs;

	/** @var int */
	public $UsuarioId;

	/** @var date */
	public $DataHora;


	/**
	 * Returns the foreign object based on the value of UsuarioId
	 * @return Responsavel
	 */
	public function GetUsuarioResponsavel()
	{
		return $this->_phreezer->GetManyToOne($this, "log_sis_ibfk_1");
	}


}
?>