<?php
/** @package Daviwebservice::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("NotasMap.php");

/**
 * NotasDAO provides object-oriented access to the notas table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Daviwebservice::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class NotasDAO extends Phreezable
{
	/** @var int */
	public $IdNotas;

	/** @var string */
	public $AvaliacaoNome;

	/** @var string */
	public $Datas;

	/** @var string */
	public $Calculo;

	/** @var float */
	public $Nota;

	/** @var int */
	public $IdNotasAluno;

	/** @var int */
	public $IdNotasMateria;


	/**
	 * Returns the foreign object based on the value of IdNotasAluno
	 * @return Aluno
	 */
	public function GetIdNotasAluno()
	{
		return $this->_phreezer->GetManyToOne($this, "notas_ibfk_1");
	}

	/**
	 * Returns the foreign object based on the value of IdNotasMateria
	 * @return Materia
	 */
	public function GetIdNotasMateria()
	{
		return $this->_phreezer->GetManyToOne($this, "notas_ibfk_2");
	}


}
?>