<?php
/** @package Daviwebservice::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ResponsavelMap.php");

/**
 * ResponsavelDAO provides object-oriented access to the responsavel table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Daviwebservice::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ResponsavelDAO extends Phreezable
{
	/** @var int */
	public $IdResp;

	/** @var string */
	public $Nome;

	/** @var string */
	public $Endereco;

	/** @var string */
	public $Cpf;

	/** @var string */
	public $Rg;


	/**
	 * Returns a dataset of Aluno objects with matching IdAlunoResp
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdAlunoRespAlunos($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "aluno_ibfk_1", $criteria);
	}

	/**
	 * Returns a dataset of LogSis objects with matching UsuarioId
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetUsuarioLogSiss($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "log_sis_ibfk_1", $criteria);
	}


}
?>